version: '3.9'

services:
  php_cli:
    container_name: test.php
    build:
      context: ../images/php-cli
    image: test
    working_dir: /usr/share/test
    volumes:
      - ../../../:/usr/share/test
    ports:
      - 8001:8001
    command: symfony server:start --port=8001
    networks:
      - test_net 
  mysql:
    container_name: test.mysql
    image: 'mariadb:10.8.2'
    ports:
      - "3306:3306"
    networks:
      - test_net
    volumes:
      - ../config/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: secret_test
      MYSQL_HOST: 127.0.0.1
      
networks:
  test_net:
